// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHD8nMEvZOAL5Mii0FCe3aB42Zcg6qXgU',
    appId: '1:859402301965:web:40c4972b636022baabdb44',
    messagingSenderId: '859402301965',
    projectId: 'fooddelivery-f77fc',
    authDomain: 'fooddelivery-f77fc.firebaseapp.com',
    storageBucket: 'fooddelivery-f77fc.appspot.com',
    measurementId: 'G-WXSBG6Q50F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqn4R92DhcJ5qDXbeo_Nq6tlZxD--ZkDY',
    appId: '1:859402301965:android:49647d3afeabf2f4abdb44',
    messagingSenderId: '859402301965',
    projectId: 'fooddelivery-f77fc',
    storageBucket: 'fooddelivery-f77fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbNNAgyYKCIjZT8hhRj2lyY2qM07TXTvI',
    appId: '1:859402301965:ios:976e893c2a32d43aabdb44',
    messagingSenderId: '859402301965',
    projectId: 'fooddelivery-f77fc',
    storageBucket: 'fooddelivery-f77fc.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbNNAgyYKCIjZT8hhRj2lyY2qM07TXTvI',
    appId: '1:859402301965:ios:14cf0df2a0e0d4d1abdb44',
    messagingSenderId: '859402301965',
    projectId: 'fooddelivery-f77fc',
    storageBucket: 'fooddelivery-f77fc.appspot.com',
    iosBundleId: 'com.example.foodDelivery.RunnerTests',
  );
}
